# Generated by Django 5.2.4 on 2025-08-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='precio',
            new_name='numero',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=20, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
    ]
